### ISSUE TITLE
Additional Command Buttons UI.

### ISSUE THREAD

**Issue by YiffLord** [zuckung/endless-sky-plugins#11]
The UI does not display the moved ammo counter for secondary weapons. 

It be gone.

**Comment by zuckung** [comment]
Theweirednut removed the ammo box in his code. You posted on the issue there, so I think you are aware of that?
The definition of its position still exists in original data and the plugin, seems it does no harm.
Am I missing something?

**Comment by zuckung** [comment]
I would love to get the ammo box back, but I think that's not in my hands^^
You may punish theweirednut with a new issue for that :)

**Comment by zuckung** [comment]
Asked to get it back ;)
https://github.com/thewierdnut/endless-mobile/issues/111

**Comment by YiffLord** [comment]
:v     
Couldn't there be a possibility to move it in the base apk?

**Comment by zuckung** [comment]
Fixed :)
