### ISSUE TITLE
Bunrodea Missions Unplayable

### ISSUE THREAD

**Issue by demolish238** [zuckung/endless-sky-plugins#12]
The initial mission for your Bunrodea missions plugin gets triggered on the capital after you talk to the queen. This means that it is impossible to complete the first mission as you cannot land on the capital again after taking off, leading to the player being unable to do any more Bunrodea missions. I've put a fix to the mission below.

mission "bunrodea defense"
	landing
	name "Bunrodea Defense"
	description "A Korath ship entered Bunrodea territory at Era Natta. Destroy it."
	source
		government "Bunrodea" "Bunrodea (Guard)"
		not planet "Erabuthro"

**Comment by zuckung** [comment]
You are right! Didn't test it right after the first contact.
Thx for reporting, fixed now.
