### ISSUE TITLE
Negative crew after hiring expert

### ISSUE THREAD

**Issue by iMacThere4iAm** [zuckung/endless-sky-plugins#13]
Departing the planet after hiring my first [expert crew member](https://github.com/zuckung/endless-sky-plugins/tree/main/myplugins/expert.crew.members/), my flagship's crew was set to -87, rendering it almost disabled. After landing and taking off again, the crew complement was restored to full. I have the `Rehire extra crew when lost` option turned on. This might be a game bug, not an issue with the plugin? Can you reproduce it?
[Save file](https://github.com/zuckung/endless-sky-plugins/files/14621306/Stud.Beefpile_exported.8.txt)
![Screenshot](https://github.com/zuckung/endless-sky-plugins/assets/713596/075afdfc-82f5-4fc0-b356-0fc42dce291c)

**Comment by zuckung** [comment]
Can't  reproduces that with my own saves, but on yours. Testing a bit atm. 
For the moment you can reload the last save when stuck in space. Then you have the expert and the crew got fixed. Though that shouldnt be possible.

**Comment by zuckung** [comment]
It has something to do with your flagship. Changing the shield Beatle to flagship let's you aquire new experts without problems. Even changing to an other kestrel works. 

First I thought the bay ships like the drones would cause this, but selling them all lets the problem persist.

So easiest would be to change the flagship and we let it be a mystery. Maybe sell that cursed kestrel?^^
Well, if you find out what exactly is causing this, let me know.
