### ISSUE TITLE
plugins crash on steam endless sky

### ISSUE THREAD

**Issue by palosbuenos** [zuckung/endless-sky-plugins#20]
when I add endless-sky-plugins-main (it doesn't appear in the plugin menu) or endless-sky-plugins-graphics-main (causes the game to crash on loading). Only way to load game is to remove endless-sky-plugins-graphics-main.

The other plugins that are loaded are BetterVanillaHai-main
BetterVanillaPirates-master
Capitalis-Major-main
Lost-in-Midnight-main
Mega-Freight-main
Prism-Plug-in-main

Are these plugins compatible with latest steam (with latest windows, 64 bit).
Was hoping to add these before I started a new game.

**Comment by zuckung** [comment]
it looks like you've pulled the whole repositories. That won't work. 

endless-sky-plugins-graphics is just a repository for the graphic files, basically for me to store the images or for people to check them out. it is not a plugin, nor are these images needed for the plugins.

and this repository is for multiple plugins, like 30 different plugins. the folder structure isn't build like a plugin, so downloading the whole repository won't work again.

if you check out the readme, and scroll down, you can see each plugin with description, informations, its own readme and a download link to the latest release zip file. use these zip files.

that should solve your problems :)
