### ISSUE TITLE
additional.command.buttons.radial removed "main menu" button

### ISSUE THREAD

**Issue by tarminu** [zuckung/endless-sky-plugins#26]
Excellent plugin, as are all of your plugins, but I miss having a "exit to main menu" button. I don't usually use a keyboard on my tablet, so no Escape key.

**Comment by zuckung** [comment]
Glad to hear that you like my plugins :)

It is no problem to add such a button.
Till now i thought every smartphone/tablet has an easy accessable "back" button which leads you to the menu?
If you still want that button, any suggestion for its position? maybe small button beside the zoom buttons? or upper screenside somewhere?

**Comment by tarminu** [comment]
My tablet, at least, makes it a pain to get the "back" button to appear when they are hidden, and in Endless Sky, swiping up from the bottom to do so usually just causes me to fire thrusters unintentionally.

Maybe above or below the fast-forward button, and about the same size?
