### ISSUE TITLE
Better Starts disables fighter bays in added/modded ships

### ISSUE THREAD

**Issue by TheMerricat** [zuckung/endless-sky-plugins#28]
Not sure why it happens, but traced it down to this mod via the ol' disable 50% of your plugins and check for the issue troubleshooting method.

With Better Starts enabled, the fighter bays of any of the ships added via plugins are ignored.

I first noticed this mid-save when I realized my mixed fleet of Korath Rano'erek (vanilla ships) and Krestels via the Kretels unlocked plugin  were carrying far less fighters than they should have been able to on paper. On testing, this seemed to be the case for all ships added via plugins, for instance when I downloaded and added Mega Freight to the mix, their ships also weren't able to use their bays.

Oddly, I don't think this impacted NPC ships, just my own.

Disabling the plugin fixes the issue immediately, even on the same save.

**Comment by TheMerricat** [comment]
Forgot to mention, tested this on continuous and 10.10. But not android.

**Comment by zuckung** [comment]
thx for reporting.
testing now.

**Comment by zuckung** [comment]
think it is fixed now. not sure why it didn't work like it was, but creating a new bay type with different name and putting the cheater 2 start ships into it seemed to solve it.
tested with cheater start 2 and kestrel.unlocks bay variant.

would be nice if you would test it too. and thx for playing my plugins :)

**Comment by TheMerricat** [comment]
That seemed to have fixed it for me as well! Thanks both for the fix and the plugins!

**Comment by zuckung** [comment]
you're welcome!
