### ISSUE TITLE
addtional command buttons plugin defines the hud interface twice.

### ISSUE THREAD

**Issue by thewierdnut** [zuckung/endless-sky-plugins#9]
You don't need to mess with `interface "hud"` to add buttons. Also, you define it twice, which means that the second instantiation overwrites the first. 

Keep in mind that if you define buttons in the hud interface, it will draw them, but nobody is checking it for events, so any clicks will be ignored. This is why I used the `interface "main buttons"` instead to draw invisible buttons over hud elements.

**Comment by zuckung** [comment]
Thanks for the input!

Didn't see that I copy&paste failed that hard, must have happend when i copied the touchscreen joystick in. And the ` interface "hud" ` is only there for resizing the message box. Think all is fixed now.

I'm not really ready for plugin release, still checking and correcting everywhere. But soon... :)
